---
title: "Coding Week Examples"
output: html_notebook
---

# Packages

```{r}
suppressPackageStartupMessages({
	library(microbenchmark)
	library(dplyr)
	library(ggplot2)
	library(data.table)
	library(visNetwork)
	#library(tictoc)
})
```

# Vectorisation / using optimised built-ins

```{r}
normal_numbers <- rnorm(100)
vec_vs_lp_res <- microbenchmark::microbenchmark(
	vector = {sum(normal_numbers)},
	loop = {
		mysum <- 0
		for(i in seq_along(normal_numbers)) {
			mysum <- mysum + normal_numbers[i]
		}
		mysum
	},
	times = 100, control = list(order = "block")#inorder
)

# boxplot(vec_vs_lp_res)

vec_vs_lp_res %>% 
	tibble::as_tibble() %>%
	ggplot(aes(expr, time)) + 
		geom_boxplot() +
		#ggbeeswarm::geom_beeswarm() +
		ggbeeswarm::geom_quasirandom() +
		scale_y_log10() + 
		labs(title = "Comparative Runtimes", y = "time /ns", x = "Condition")
```

# Growing scaling

```{r}
lengths <- seq(1, 1000, length.out = 10)
lst <- vector(mode = "list", length = length(lengths))
for (i in seq_along(lengths)) {
	n <- lengths[i]
	lst[[i]] <- microbenchmark::microbenchmark(
		grow = {
			vec <- numeric(0)
			for(i in 1:n) vec <- c(vec, i)
		},
		"pre-allocate" = {
			vec <- numeric(n)
			for(i in 1:n) vec[i] <- i
		},
		direct = {
			vec <- 1:n
		},
		times = 50
	) %>% 
		tibble::as_tibble() %>%
		dplyr::mutate(length = n)
}
effect_of_vec_len <- dplyr::bind_rows(lst)

effect_of_vec_len %>%
	ggplot(., aes(length, time)) +
	#geom_point(aes(color = expr), size = 0.2) + 
	scale_y_log10() +
	#geom_line(aes(color = expr)) + 
	geom_smooth(
		aes(color = expr),
		#method = "lm", formula = "y ~ x"
		method = "gam", formula = y ~ s(x, bs = "cs")
	) + 
	theme_bw() + 
	labs(
		title = "Change in runtime with number of iterations",
		y = "time /ns", color = "Condition",
		x = "Length of vector"
	) 


```


# Growing

```{r}
n <- 100
n_bench <- 50
object_creation <- microbenchmark::microbenchmark(
	grow = {
		vec <- numeric(0)
		for(i in 1:n) vec <- c(vec, i)
	},
	"pre-allocate" = {
		vec <- numeric(n)
		for(i in 1:n) vec[i] <- i
	},
	direct = {
		vec <- 1:n
	},
	times = n_bench
)

#boxplot(object_creation)

object_creation %>%
	as_tibble() %>%
	ggplot(aes(expr, time)) + 
		#ggbeeswarm::geom_beeswarm() +
		ggbeeswarm::geom_quasirandom(size = 0.2) +
		geom_boxplot(outlier.shape = NA, fill = NA, color = "red") +
		scale_y_log10() + 
		labs(title = "Comparative Runtimes", y = "time /ns", x = "Condition") + 
		theme_bw()
```

# Growing a data.frame


```{r}
n <- 100
n_bench <- 50
df_creation <- microbenchmark::microbenchmark(
	grow = {
		df <- data.frame(A = integer())
		for(i in 1:n) df <- rbind(df, data.frame(A = i))
	},
	"pre-allocate" = {
		df <- data.frame(A = integer(length = n))
		for(i in 1:n) df[i, 1] <- i
	},
	direct = {
		df <- data.frame(A = 1:n)
	},
	times = n_bench
)

#boxplot(object_creation)

df_creation %>%
	as_tibble() %>%
	ggplot(aes(expr, time)) + 
		#ggbeeswarm::geom_beeswarm() +
		ggbeeswarm::geom_quasirandom(size = 0.2) +
		geom_boxplot(outlier.shape = NA, fill = NA, color = "red") +
		scale_y_log10() + 
		labs(title = "Comparative Runtimes", y = "time /ns", x = "Condition") + 
		theme_bw()
```

```{r}
lengths <- seq(1, 1000, length.out = 10)
lst <- vector(mode = "list", length = length(lengths))
for (i in seq_along(lengths)) {
	n <- lengths[i]
	lst[[i]] <- microbenchmark::microbenchmark(
	grow = {
		df <- data.frame(A = integer())
		for(i in 1:n) df <- rbind(df, data.frame(A = i))
	},
	"pre-allocate" = {
		df <- data.frame(A = integer(length = n))
		for(i in 1:n) df[i, 1] <- i
	},
	direct = {
		df <- data.frame(A = 1:n)
	},
	times = n_bench
	) %>% 
		tibble::as_tibble() %>%
		dplyr::mutate(length = n)
}
effect_of_vec_len_df <- dplyr::bind_rows(lst)

effect_of_vec_len_df %>%
	ggplot(., aes(length, time)) +
	#geom_point(aes(color = expr), size = 0.2) + 
	scale_y_log10() +
	#geom_line(aes(color = expr)) + 
	geom_smooth(
		aes(color = expr),
		#method = "lm", formula = "y ~ x"
		method = "gam", formula = y ~ s(x, bs = "cs")
	) + 
	theme_bw() + 
	labs(
		title = "Change in runtime with number of iterations",
		y = "time /ns", color = "Condition",
		x = "Length of vector"
	) 
```


```{r}
dplyr::bind_rows(
	effect_of_vec_len %>% dplyr::mutate(type = "vector"),
	effect_of_vec_len_df %>% dplyr::mutate(type = "data.frame")
) %>%
	ggplot(., aes(length, time)) +
	#geom_point(aes(color = expr), size = 0.2) + 
	scale_y_log10(labels = scales::comma) +
	#geom_line(aes(color = expr)) + 
	geom_smooth(
		aes(color = expr),
		#method = "lm", formula = "y ~ x"
		method = "gam", formula = y ~ s(x, bs = "cs")
	) + 
	theme_bw() + 
	labs(
		#title = "Pre-allocating data.frames is still faster",
		title = "Vector growth faster now, df pre-allocation still faster",
		subtitle = "Runtime by length",
		y = "time /ns", color = "Condition",
		x = "Length of vector"
	) +
	facet_wrap(~type)
```


# Vectorisation

```{r}
amat <- matrix(rnorm(10000), nrow = 100)
subsetting_vectors <- microbenchmark::microbenchmark(
	"subsetting, loop" = {
		bmat <- matrix(NA, nrow(amat)/2, ncol(amat))
		for(i in 1:nrow(bmat)) bmat[i,] <- amat[2*i-1,] * amat[2*i,]
	},
	"subsetting, vectorised" = {
		bmat2 <- amat[seq(1, nrow(amat), by=2),] *
		amat[seq(2, nrow(amat), by=2),]
	},
	times = 50
) 
#all.equal(bmat, bmat2)


subsetting_vectors %>%
	as_tibble() %>%
	ggplot(aes(expr, time)) + 
		geom_boxplot() +
		#ggbeeswarm::geom_beeswarm() +
		ggbeeswarm::geom_quasirandom() +
		scale_y_log10() + 
		labs(title = "Comparative Runtimes", y = "time /ns", x = "Condition")

```

# Hash tables

https://blog.dominodatalab.com/a-quick-benchmark-of-hashtable-implementations-in-r

```{r}
myenv <- new.env(hash=TRUE) 
myenv$tmp <- "test"

myenv$tmp
```


```{r}
set.seed(42)
#n <- 1e5
#n <- 1e3
n <- 1e5
values <- 1:n

keys <- purrr::map_chr(1:n, ~paste0(
	sample(c(letters, LETTERS, 1:100),sample(10:15,1)),
	collapse = ""
))
# Ensure that all n keys are unique
keys <- unique(keys)
length(keys)
while(length(keys) < n) {
	nn <- n - length(keys)
	new_keys <- purrr::map_chr(1:nn, ~paste0(
		sample(c(letters, LETTERS, 1:100),sample(10:15,1)),
		collapse = ""
	))
	keys <- unique(c(keys, new_keys))
}
length(keys)



object_construction <- microbenchmark::microbenchmark(
	"named vector" = {
		named_vec <- values
		names(named_vec) <- keys
	},
	"named list" = {
		named_lst <- as.list(named_vec)
	},
	"hash" = {
		my_env <- new.env(hash=TRUE) 
		purrr::walk2(keys, values, ~{my_env[[.x]] <- .y})
	},
	"data.frame" = {
		df <- data.frame(keys = keys, values = values)
	},
	"indexed data.table" = {
		dt <- data.table(keys = keys, values = values)
		setkey(dt, keys) 
	},
	times = 100
) %>% 
	tibble::as_tibble() %>%
	dplyr::mutate(length = n)

```

```{r}
n_bench <- 13
lengths <- round(seq(1, 1e5, length.out = 20))
lst <- vector(mode = "list", length = length(lengths))
lstr <- vector(mode = "list", length = length(lengths))
for (i in seq_along(lengths)) {
	n <- lengths[i]
	values <- 1:n
	
	keys <- purrr::map_chr(1:n, ~paste0(
		sample(c(letters, LETTERS, 1:100),sample(10:15,1)),
		collapse = ""
	))
	# Ensure that all n keys are unique
	keys <- unique(keys)
	length(keys)
	while(length(keys) < n) {
		nn <- n - length(keys)
		new_keys <- purrr::map_chr(1:nn, ~paste0(
			sample(c(letters, LETTERS, 1:100),sample(10:15,1)),
			collapse = ""
		))
		keys <- unique(c(keys, new_keys))
	}
	length(keys)
	
	named_vec <- values
	names(named_vec) <- keys
	
	lst[[i]] <- microbenchmark::microbenchmark(
		"named vector" = {
		named_vec <- values
		names(named_vec) <- keys
	},
	"named list" = {
		named_lst <- as.list(named_vec)
	},
	"hash" = {
		my_env <- new.env(hash=TRUE) 
		purrr::walk2(keys, values, ~{my_env[[.x]] <- .y})
	},
	"data.frame" = {
		df <- data.frame(keys = keys, values = values)
	},
	"indexed data.table" = {
		dt <- data.table(keys = keys, values = values)
		setkey(dt, keys) 
	},
	times = n_bench
	) %>% 
		tibble::as_tibble() %>%
		dplyr::mutate(length = n, type = "Construction")
	
	example_key <- sample(keys, 1)
	
	named_lst <- as.list(named_vec)
	
	my_env <- new.env(hash=TRUE) 
	purrr::walk2(keys, values, ~{my_env[[.x]] <- .y})
	
	dt <- data.table(keys = keys, values = values)
	setkey(dt, keys) 
	
	df <- data.frame(keys = keys, values = values)
	
	lstr[[i]] <- microbenchmark::microbenchmark(
		"named vector" = {
			named_vec[example_key]
		},
		"named list" = {
			named_lst[example_key]
		},
		"hash" = {
			my_env[[example_key]]
		},
		"data.frame" = {
			df[df$keys == example_key,]
		},
		"indexed data.table" = {
			dt[keys == example_key]
			#dt[keys == example_key][[2]]
		},
		times = n_bench
	) %>% 
		tibble::as_tibble() %>%
		dplyr::mutate(length = n, type = "Retreival")

}
effect_of_vec_len <- dplyr::bind_rows(lst,lstr)
```

```{r, fig.width=12, fig.height=6.75}
effect_of_vec_len %>%
	ggplot(., aes(length, time)) +
	scale_y_log10() +
	geom_smooth(
		aes(color = expr),
		#method = "lm", formula = "y ~ x"
		method = "gam", formula = y ~ s(x, bs = "cs")
	) + 
	theme_bw() + 
	labs(
		title = "Change in runtime with number of elements",
		y = "time /ns", color = "Condition",
		x = "Length of vector"
	) +
	facet_wrap(~type, ncol = 2)
```

## paralelle debug

```{r}
library(data.table)
n_bench <- 5
lengths <- round(seq(1, 1e2, length.out = 3))
lst <- vector(mode = "list", length = length(lengths))
lstr <- vector(mode = "list", length = length(lengths))
maxn <- max(lengths)
values <- 1:maxn

# Key value pairs generated outside the main benchmarking loop 
# in the max length required adn subset within the loop to 
# save on the expensive operation of random key generation
# and uniqueness checking
keys <- purrr::map_chr(1:maxn, ~paste0(
	sample(c(letters, LETTERS, 1:100), sample(10:15, 1)),
	collapse = ""
))
# Ensure that all n keys are unique
keys <- unique(keys)
#length(keys)
while(length(keys) < maxn) {
	nn <- maxn - length(keys)
	new_keys <- purrr::map_chr(1:nn, ~paste0(
		sample(c(letters, LETTERS, 1:100),sample(10:15,1)),
		collapse = ""
	))
	keys <- unique(c(keys, new_keys))
}
# The {furrr} package parallelises the {purr} map functions using {future}
#furrr::future_walk(
furrr::future_map_dfr(
	.options = furrr_options(
		seed = 42#, globals = c("lst","lstr", "lengths", "keys", "values")
	),
	seq_along(lengths), ~{
	i <- .x
	n <- lengths[i]
	# random subset of key value pairs of the appropriate length
	values <- sample(values, n) 
	keys <- keys[values]
	named_vec <- values
	names(named_vec) <- keys
	
	#lst[[i]] 
	lst <- microbenchmark::microbenchmark(
		"named vector" = {
			named_vec <- values
			names(named_vec) <- keys
		},
		"named list" = {
			named_lst <- as.list(named_vec)
		},
		"hash" = {
			my_env <- new.env(hash = TRUE) 
			purrr::walk2(keys, values, ~{my_env[[.x]] <- .y})
		},
		"data.frame" = {
			df <- data.frame(keys = keys, values = values)
		},
		"indexed data.table" = {
			dt <- data.table(keys = keys, values = values)
			setkey(dt, keys) 
		},
		times = n_bench
	) %>% 
		tibble::as_tibble() %>%
		dplyr::mutate(length = n, type = "Construction")
	
	example_key <- sample(keys, 1)
	
	named_lst <- as.list(named_vec)
	
	my_env <- new.env(hash = TRUE) 
	purrr::walk2(keys, values, ~{my_env[[.x]] <- .y})
	
	# doesnot work multisession - maybe multicore? unlikely
	# see mc_env_assign.R
	#furrr::future_walk2(keys, values, ~{my_env[[.x]] <- .y})
	
	dt <- data.table(keys = keys, values = values)
	setkey(dt, keys) 
	
	df <- data.frame(keys = keys, values = values)
	
	#lstr[[i]]
	lstr <- microbenchmark::microbenchmark(
		"named vector" = {
			named_vec[example_key]
		},
		"named list" = {
			named_lst[example_key]
		},
		"hash" = {
			my_env[[example_key]]
		},
		"data.frame" = {
			df[df$keys == example_key,]
		},
		"indexed data.table" = {
			dt[keys == example_key]
			#dt[keys == example_key][[2]]
		},
		times = n_bench
	) %>% 
		tibble::as_tibble() %>%
		dplyr::mutate(length = n, type = "Retreival")
	
	dplyr::bind_rows(lst,lstr)
})
#effect_of_vec_len <- dplyr::bind_rows(lst,lstr)
effect_of_vec_len
```



## non-member

```{r}
non_member <- dplyr::bind_rows(
	microbenchmark::microbenchmark({
		"not here" %in% named_vec
	}),
	microbenchmark::microbenchmark({
		!is.null(named_lst[["not here"]])
	}),
	microbenchmark::microbenchmark({
		!is.null(my_env[["not here"]])
	}) %>%
	dplyr::mutate(
		name = dplyr::case_when(
			grepl("named_lst", expr) ~ "named list",
			grepl("%in%", expr) ~ "named vector",
			grepl("null", expr) ~ "hash"
		)
	)
)

non_member

non_member %>%
	as_tibble() %>%
	ggplot(aes(expr, time)) + 
		geom_boxplot() +
		#ggbeeswarm::geom_beeswarm() +
		ggbeeswarm::geom_quasirandom() +
		scale_y_log10() + 
		labs(title = "Comparative Runtimes", y = "time /ns", x = "Condition")
```


## Indexing a data.frame

```{r}
df <- data.frame(keys = keys, values = values)


df_l <- df %>% group_by(keys) %>% dplyr::group_split()
names(df_l) <- df$keys
df_index <- new.env(hash = TRUE)
purrr::walk2(df$keys, df_l, ~{df_index[[.x]] <- .y})

hash_as_index <- dplyr::bind_rows(
	microbenchmark::microbenchmark({
		df_index[[example_key]]
	}),
	microbenchmark::microbenchmark({
		df %>% dplyr::filter(keys == example_key)
	}) %>%
	dplyr::mutate(
		name = dplyr::case_when(
			grepl("filter", expr) ~ "dplyr filter",
			grepl("df_index", expr) ~ "hash"
		)
	)
)

hash_as_index


hash_as_index %>%
	as_tibble() %>%
	ggplot(aes(name, time)) + 
		geom_boxplot() +
		#ggbeeswarm::geom_beeswarm() +
		ggbeeswarm::geom_quasirandom() +
		scale_y_log10() + 
		labs(title = "Comparative Runtimes", y = "time /ns", x = "Condition")
```


# Benchmarking libraries

- microbenchmark https://cran.r-project.org/package=microbenchmark
- rbenchmark https://cran.r-project.org/package=rbenchmark
- bench https://github.com/r-lib/bench


R trivia R = S-1, as no unaray operator ++


# $> EXERCISE

```{r}
x <- matrix(rnorm(1e5, mean = 1), nrow = 100)
x[sample(seq_along(x), 1000)] <- NA

tictoc::tic()
if(all(!is.na(x))) {
	if(mean(x) > 0) {
		summary(as.vector(x))
	}
}
tictoc::toc()
```

```{r}
# We only calculate the mean if data doesn't contain NAs
tictoc::tic()
if(all(!is.na(x)) && mean(x) > 0) {
	summary(as.vector(x))
}
tictoc::toc()
```


# if else

```{r}
lengths <- seq(1, 1000, length.out = 50)
lst <- vector(mode = "list", length = length(lengths))
marks <- sample(1:100, 1000, replace = TRUE)
for (i in seq_along(lengths)) {
	n <- lengths[i]
	lst[[i]] <- microbenchmark::microbenchmark(
		"base::ifelse" = {
			ifelse(marks[1:n] >= 40, "pass", "fail")
		},
		"dplyr::if_else" = {
			dplyr::if_else(marks[1:n] >= 40, "pass", "fail")
		},
		"vector" = {
			results <- rep("fail", length(marks[1:n]))
			results[marks[1:n] >= 40] <- "pass"
		},
		"long_if_else" = {
			purrr::map_chr(marks[1:n], ~{
				if(.x >= 40) {
					"pass"
				} else {
					"fail"
				}
			})
		},
		"long_switch" = {
			purrr::map_chr(marks[1:n], ~{
				switch(
					as.character(.x >= 40), "TRUE" = "pass", "FALSE" = "fail"
				)
			})
		},
		times = 20
	) %>% 
		tibble::as_tibble() %>%
		dplyr::mutate(length = n)
}
if_else_comparisons <- dplyr::bind_rows(lst)

if_else_comparisons %>%
	ggplot(., aes(length, time)) +
	#geom_point(aes(color = expr), size = 0.2) + 
	scale_y_log10() +
	#geom_line(aes(color = expr)) + 
	geom_smooth(
		aes(color = expr),
		#method = "lm", formula = "y ~ x"
		method = "gam", formula = y ~ s(x, bs = "cs")
	) + 
	theme_bw() + 
	labs(
		title = "Comparison of 'ifelse' methods",
		y = "time /ns", color = "Condition",
		x = "Length of vector"
	) 


```


# sorting

```{r}
max_len <- 1e3
n_bench <- 5
lengths <- round(seq(10, max_len, length.out = 5))
lst <- vector(mode = "list", length = length(lengths))
marks <- sample(1:100, max_len, replace = TRUE)
strings <- purrr::map_chr(1:max_len, ~paste0(
	sample(c(letters, LETTERS, 1:10),sample(10:15,1)),
	collapse = ""
))
for (i in seq_along(lengths)) {
	n <- lengths[i]
	lst[[i]] <- microbenchmark::microbenchmark(
		"numeric_auto_fwd_complete" = {
			sort(marks[1:n])
		},
		"numeric_auto_decreasing_complete" = {
			sort(marks[1:n], decreasing = TRUE)
		},
		"numeric_auto_rev_complete" = {
			rev(sort(marks[1:n]))
		},
		"numeric_auto_fwd_partial10" = {
			sort(marks[1:n], partial = 1:10)
		},
		
		"strings_auto_fwd_complete" = {
			sort(strings[1:n])
		},
		"strings_auto_decreasing_complete" = {
			sort(strings[1:n], decreasing = TRUE)
		},
		"strings_auto_rev_complete" = {
			rev(sort(strings[1:n]))
		},
		"strings_auto_fwd_partial10" = {
			sort(strings[1:n], partial = 1:10)
		},
		
		"numeric_shell_fwd_complete" = {
			sort(marks[1:n], method = "shell",)
		},
		"numeric_quick_fwd_complete" = {
			sort(marks[1:n], method = "quick")
		},
		"numeric_radix_fwd_complete" = {
			sort(marks[1:n], method = "radix")
		},
		
		"strings_shell_fwd_complete" = {
			sort(strings[1:n], method = "shell",)
		},
		"strings_quick_fwd_complete" = {
			sort(strings[1:n], method = "quick")
		},
		"strings_radix_fwd_complete" = {
			sort(strings[1:n], method = "radix")
		},
		times = n_bench
	) %>% 
		tibble::as_tibble() %>%
		dplyr::mutate(length = n) %>%
		#tidyr::extract(
		tidyr::separate(
			expr, into = c("type", "method", "direction", "complete"), sep = "_",
			#regex = "(\\w+)_method_(\\w+)_(\\w+)",
			remove = FALSE
		)
}
sort_comparisons <- dplyr::bind_rows(lst)
```


```{r}
sort_comparisons %>%
	dplyr::filter(
		#direction == "fwd",
		method == "auto",
		complete == "complete"
	) %>%
	ggplot(., aes(length, time)) +
	#geom_point(aes(color = expr), size = 0.2) + 
	scale_y_log10() +
	#geom_line(aes(color = expr)) + 
	geom_smooth(
		aes(color = paste(method, direction)),
		#method = "lm", formula = "y ~ x"
		method = "gam", formula = y ~ s(x, bs = "cs")
	) + 
	theme_bw() + 
	facet_grid(~type) +
	labs(
		title = "forward, decreasing or reverse?",
		y = "time /ns", color = "Condition",
		x = "Length of vector"
	) 
```

```{r}
sort_comparisons %>%
	dplyr::filter(
		#direction == "fwd",
		method != "auto",
		complete == "complete"
	) %>%
	ggplot(., aes(length, time)) +
	#geom_point(aes(color = expr), size = 0.2) + 
	scale_y_log10() +
	#geom_line(aes(color = expr)) + 
	geom_smooth(
		aes(color = method),
		#method = "lm", formula = "y ~ x"
		method = "gam", formula = y ~ s(x, bs = "cs")
	) + 
	theme_bw() + 
	facet_grid(~type) +
	labs(
		title = "Sort algorithms (radix is default)",
		y = "time /ns", color = "Condition",
		x = "Length of vector"
	) 
```

```{r}
sort_comparisons %>%
	dplyr::filter(
		direction == "fwd",
		method == "auto"#,
		#complete != "complete"
	) %>%
	ggplot(., aes(length, time)) +
	#geom_point(aes(color = expr), size = 0.2) + 
	scale_y_log10() +
	#geom_line(aes(color = expr)) + 
	geom_smooth(
		aes(color = complete),
		#method = "lm", formula = "y ~ x"
		method = "gam", formula = y ~ s(x, bs = "cs")
	) + 
	theme_bw() + 
	facet_grid(~type) +
	labs(
		title = "Partial sorting (e.g. just top 10)",
		y = "time /ns", color = "Condition",
		x = "Length of vector"
	) 
```


```{r}
nvec <- sample(1:100, 1e6, replace = TRUE)
nvec[sample(1:1e6, 5e3)] <- NA_integer_
tic()
any(is.na(nvec))
toc()
tic()
anyNA(nvec)
toc()
```

